BurgerMVC/Areas/Admin/Controllers/AdminGraficoController.cs
using BurgerMVC.Areas.Services;
using Microsoft.AspNetCore.Mvc;

namespace BurgerMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminGraficoController : Controller
    {
        private readonly GraficoVendasService _graficoVendasService;

        public AdminGraficoController(GraficoVendasService graficoVendasService)
        {
            _graficoVendasService = graficoVendasService ??
                throw new ArgumentNullException(nameof(graficoVendasService));
        }

        public JsonResult VendasLanches(int dias)
        {
            var lanchesVendasTotais = _graficoVendasService.GetVendasLanche(dias);
            return Json(lanchesVendasTotais) ;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult VendasMensal()
        {
            return View();
        }
        [HttpGet]
        public IActionResult VendasSemanal()
        {
            return View();
        }
    }
}

BurgerMVC/Areas/Admin/Views/AdminGrafico/Index.cshtml
<title>
    @ViewData["Title"] - Grafico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">

    google.charts.load('current', { packages: ['corechart', 'bar'] });
    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: { dias: 360 },
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function (data) {
                GraficoVendasLanches(data);
                return false;
            }
        });
        return false;
    }

    function GraficoVendasLanches(data) {
      
         var dataArray = [

            [{label: 'Lanche', type: 'string'},

            {label: 'Quantidade', type: 'number' },

            {label: 'Valores(R$)', type: 'number' }]

        ];
        $.each(data, function(i, item){
            dataArray.push([item.nomeLanche, item.quantidade, item.lanchesValorTotal]);
        });
        
        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 360 dias',
            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Valor Total (em Reais)',
                minValue: 0
            },
            vAxis: {
                title: 'Lanches'
            }
        };
       
        var chart = new google.visualization.BarChart(document.getElementById('chart_div'));
        chart.draw(data, options);
       
    }
</script>

BurgerMVC/Areas/Admin/Views/AdminGrafico/VendasMensal.cshtml
<title>
    @ViewData["Title"] - Grafico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">

    google.charts.load('current', { packages: ['corechart', 'bar'] });
    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: { dias: 30 },
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function (data) {
                GraficoVendasLanches(data);
                return false;
            }
        });
        return false;
    }

    function GraficoVendasLanches(data) {

        var dataArray = [

            [{ label: 'Lanche', type: 'string' },

            { label: 'Quantidade', type: 'number' },

            { label: 'Valores(R$)', type: 'number' }]

        ];
        $.each(data, function (i, item) {
            dataArray.push([item.nomeLanche, item.quantidade, item.lanchesValorTotal]);
        });

        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 30 dias',
            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Lanches',
                minValue: 0
            },
            vAxis: {
                title: 'Valor Total (em reais)'
            }
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
        chart.draw(data, options);

    }
</script>

BurgerMVC/Areas/Admin/Views/AdminGrafico/VendasSemanal.cshtml
<title>
    @ViewData["Title"] - Grafico de Vendas
</title>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<div id="chart_div" style="width: 900px; height: 500px;"></div>

<script type="text/javascript">

    google.charts.load('current', { packages: ['corechart', 'bar'] });
    google.charts.setOnLoadCallback(CarregaDados);

    function CarregaDados() {
        $.ajax({
            url: '@Url.Action("VendasLanches", "AdminGrafico")',
            data: { dias: 7 },
            dataType: "json",
            type: "GET",
            error: function (xhr, status, error) {
                var err = eval("(" + xhr.responseText + ")");
                toastr.error(err.message);
            },
            success: function (data) {
                GraficoVendasLanches(data);
                return false;
            }
        });
        return false;
    }

    function GraficoVendasLanches(data) {

        var dataArray = [

            [{ label: 'Lanche', type: 'string' },

            { label: 'Quantidade', type: 'number' },

            { label: 'Valores(R$)', type: 'number' }]

        ];
        $.each(data, function (i, item) {
            dataArray.push([item.nomeLanche, item.quantidade, item.lanchesValorTotal]);
        });

        var data = google.visualization.arrayToDataTable(dataArray);
        var options = {
            title: 'Lanches - Vendas nos últimos 7 dias',
            chartArea: {
                width: '70%'
            },
            colors: ['#5202b5', '#d2a828'],
            hAxis: {
                title: 'Valor Total (em Reais)',
                minValue: 0
            },
            vAxis: {
                title: 'Lanches'
            }
        };

        var chart = new google.visualization.SteppedAreaChart(document.getElementById('chart_div'));
        chart.draw(data, options);

    }
</script>