BurgerMVC/Controllers/CarrinhoDeCompraController.cs
using BurgerMVC.Context;
using BurgerMVC.Models;
using BurgerMVC.Models.ViewModels;
using BurgerMVC.Repository.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BurgerMVC.Controllers
{
    [Authorize]
    public class CarrinhoDeCompraController : Controller
    {

        private readonly CarrinhoCompra _carrinhoCompras;
        private readonly ILancheRepository _lancheRepository;

        public CarrinhoDeCompraController(CarrinhoCompra carrinhoCompra, ILancheRepository lancheRepository)
        {
            _carrinhoCompras = carrinhoCompra;
            _lancheRepository = lancheRepository;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompras.GetItensDoCarrinhos();
            _carrinhoCompras.CarrinhoCompraItens = itens;

            var itensVm = new CarrinhoCompraViewModel
            {
                carrinhoCompra = _carrinhoCompras,
                CarrinhoCompraTotal = _carrinhoCompras.Total()
            };

            return View(itensVm);
        }

        public IActionResult AddItemCarrinho(int id)
        {
            var result = _lancheRepository.Lanches.FirstOrDefault(x => x.LancheId == id);

            if (result != null)
            {
                _carrinhoCompras.AddItem(result);
            }
            return RedirectToAction(nameof(Index));

        }
        public IActionResult RemoveItemCarrinho(int id)
        {
            var result = _lancheRepository.Lanches.FirstOrDefault(x => x.LancheId == id);

            if (result != null)
            {

                _carrinhoCompras.RemoverItem(result);
            }
            return RedirectToAction(nameof(Index));

        }

    }
}

BurgerMVC/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace BurgerMVC.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BurgerMVC/Controllers/LancheController.cs
using BurgerMVC.Models;
using BurgerMVC.Models.ViewModels;
using BurgerMVC.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace BurgerMVC.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        public LancheController(ILancheRepository lancheRepository)
        {
            _lancheRepository = lancheRepository;
        }
        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string novaCategoria = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(x => x.Nome).ToList();
                novaCategoria = "Todos os lanches";
            }
            else

            {

                lanches = _lancheRepository.Lanches.Where(x => x.Categoria.CategoriaNome.Equals(categoria)).OrderBy(x => x.Nome);
                novaCategoria = categoria;
            }



            var lanchesListVM = new LanchesViewModel
            {
                Lanches = lanches,
                NovaCategoria = novaCategoria
            };
            return View(lanchesListVM);
        }

        public async Task<IActionResult> Details(int id)
        {
            var lancheDet = await _lancheRepository.GetLancheById(id);
            return View(lancheDet);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                lanches = _lancheRepository.Lanches.OrderBy(x => x.LancheId);
                categoriaAtual = "todos os lanches";
            }

            else
            {
                lanches = _lancheRepository.Lanches.Where(x => x.Nome.ToLower().Contains(searchString.ToLower()));
                if (lanches.Any())
                {
                    categoriaAtual = "lanches";
                }
                else
                {
                    categoriaAtual = "Nenhum lanche foi encontrado";
                }
            }
            return View("~/Views/Lanche/List.cshtml", new LanchesViewModel
            {
                Lanches = lanches,
                NovaCategoria = categoriaAtual
            });

        }

    }
}

BurgerMVC/Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/carousel11.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel12.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel13.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselLanches" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselLanches" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

BurgerMVC/Views/Shared/_LanchesResumo.cshtml
@model Lanche

<div class="col-sm-4 col-md-4 col-lg-4">
    <p><img src="@Model.ImagemUrl"></p>
    <h3>Preço : @Model.Preco.ToString("c")</h3>
    @* asp-route-tem que ser o msm nome do parametro que passa na action no controlador*@
    <h4><a asp-controller="Lanche" asp-action="Details" asp-route-id="@Model.LancheId">@Model.Nome</a></h4>
    <p>
        <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoDeCompra" asp-action="AddItemCarrinho" asp-route-id="@Model.LancheId">
            adicionar @Model.Nome no carrinho
        </a>
    </p>

</div>

BurgerMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BurgerMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BurgerMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow  mb-3">
            <div class="container ">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BurgerMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse flex-grow-0 ">
                    <partial name="_LoginPartial" />
                    @await Component.InvokeAsync("CategoriaMenu")
                  
                    <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                   
                    <form class="d-flex" role="search" asp-controller="Lanche" asp-action="Search" method="get">
                        <input class="form-control me-2" type="search" placeholder="Procurar produto" name="searchString"
                        value="@ViewData["searchString"]">
                        
                    </form>
                    @await Component.InvokeAsync("CarrinhoCompraResumo")
                    @if (User.IsInRole("Admin"))
                    {

                       <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin area</a>

                    }    
                </div>
                
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BurgerMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>