BurgerMVC/Areas/Admin/Controllers/AdminImagesController.cs
using BurgerMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Data;

namespace BurgerMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AdminImagesController : Controller
    {
        private readonly ConfigurationImages _myConfig;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AdminImagesController(IOptions<ConfigurationImages> myConfig, IWebHostEnvironment webHostEnvironment)
        {
            _myConfig = myConfig.Value;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> UploadFiles(List<IFormFile> files)
        {
            if (files == null || files.Count == 0)
            {
                ViewData["erro"] = "Arquivo não selecionado";
                return View(ViewData);
            }
            if (files.Count > 10)
            {
                ViewData["Erro"] = "A quantidade de arquivos excedeu o limite";
                return View(ViewData);
            }

            long size = files.Sum(x => x.Length);
            var pathName = new List<string>();
            var filePath = Path.Combine(_webHostEnvironment.WebRootPath,
                _myConfig.NomePastaImagensProdutos);

            foreach (var formFile in files)
            {
                if (formFile.FileName.Contains(".jpg") || formFile.FileName.Contains(".gif") || formFile.FileName.Contains(".png"))
                {
                    var fileNameWithPath = string.Concat(filePath, "\\", formFile.FileName);

                    pathName.Add(fileNameWithPath);
                    using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                    }
                }
            }

            ViewData["Resultado"] = $"{files.Count} arquivos foram enviados, " + $"com o tamanho de {size} bytes";
            ViewBag.Arquivos = pathName;

            return View(ViewData);


        }

        public IActionResult GetImages()
        {
            FileManagerModel model = new FileManagerModel();
            var userImagesPath = Path.Combine(_webHostEnvironment.WebRootPath, _myConfig.NomePastaImagensProdutos);

            DirectoryInfo dir = new DirectoryInfo(userImagesPath);

            FileInfo[] files = dir.GetFiles();

            model.PathImageProduto = _myConfig.NomePastaImagensProdutos;
            if (files.Length > 0)
            {
                ViewData["Erro"] = $"nenhum arquivo selecionado {userImagesPath}";
            }
            model.Files = files;
            return View(model);

        }
        public IActionResult DeleteFiles(string fileName)
        {
            string _imageDelete = Path.Combine(_webHostEnvironment.WebRootPath,
                _myConfig.NomePastaImagensProdutos + "\\",fileName);
            if(System.IO.File.Exists(_imageDelete))
            {
                System.IO.File.Delete(_imageDelete);
                ViewData["Deletado"] = $"Arquivo {_imageDelete} deletado com sucesso";

            }
            return View("Index");
            
        }

    }
}

BurgerMVC/Areas/Admin/Views/AdminImages/GetImages.cshtml
@model FileManagerModel
@{
    ViewBag.Title = "Arquivos";
}
@if (Model.Files != null)
{
    <h3>Imagens:</h3>
    <hr />
    var caminho = Model.PathImageProduto;
    <div class="row">
        @foreach (FileInfo file in Model.Files)
        {
            <div class="column">
                <img src="~/@caminho/@file.Name" width="125" height="125" title="@file.Name" asp-append-version="true">
                <div style="padding:10px;text-align:left">
                    <a href="@Url.Action("DeleteFiles","AdminImages",new { fileName=file.Name})">Deletar</a>
                </div>
            </div>
        }
    </div>
}
@if (ViewData["Erro"] == null)
{
    <img src="~/images/erro1.png" width="150" height="150" />
    <h4>@ViewData["Erro"]</h4>
}
<div class="clearfix"></div>
<hr />
<div>
    <span>Para ver o nome do arquivo passa o mouse na imagem</span>
</div>
<div class="form-group">
    <a class="btn btn-outline-info" asp-controller="AdminImages" asp-action="Index">Retornar</a>
</div>

BurgerMVC/Areas/Admin/Views/AdminImages/Index.cshtml
<br />
<h4><strong>Gerenciar Imagens</strong></h4>
<br />
<table border="0" width="100%">
    <tr>
        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImages" asp-action="UploadFiles">
                <img src="~/images/upload2.png" width="200" height="150" />
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <p><b>Selecione um ou mais arquivos para enviar :</b></p>
                        <p>(Arquivos com o mesmo nome serão sobrescritos)</p>
                        <input type="file" name="files" multiple class="button btn-primary" />
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Enviar Arquivo(s)" class="button btn-outline-primary" />
                    </div>
                </div>
            </form>
        </td>
        <td>
            <form method="post" enctype="multipart/form-data" asp-controller="AdminImages" asp-action="GetImages">
                <img src="~/images/visualizar1.jpg" width="200" height="200" />
                <div class="form-group">
                    <div class="col-md-10">
                        <p><strong>Visualizar Imagens na pasta do servidor :</strong></p>
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Visualizar Arquivos no servidor" class="button btn-outline-warning" />
                    </div>
                </div>
            </form>
        </td>
    </tr>
</table>
<div class="container">
    @if (ViewData["Deletado"] != null)
    {
        <ul>
            <li>@ViewData["Deletado"]</li>
        </ul>
       
    }
</div>

BurgerMVC/Areas/Admin/Views/AdminImages/UploadFiles.cshtml
@{
    ViewData["Title"] = "Upload Files";
}
<img src="~/images/upload2.png" width="200" height="150" />
<hr />
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        @if (ViewData["Erro"] != null)
        {
            <img src="~/images/erro1.png" width="150" height="150" />
            <h4>@ViewData["Erro"]</h4>
        }
    </div>
    <div class="container">
        @if (ViewData["Resultado"] != null)
        {
            <h4>@ViewData["Resultado"]</h4>
            <hr />
            @if (ViewBag.Arquivos != null)
            {
                @foreach (string arquivo in ViewBag.Arquivos)
                {
                    <ul>
                        <li>
                            @arquivo
                        </li>
                    </ul>

                }
            }
        }
    </div>
</div>
<div class="form-group">
    <a class="btn btn-outline-info" asp-controller="AdminImages" asp-action="GetImages">Exibir Imagens</a>
</div>